spring:
  application:
    name: KOSMEETING
  datasource:
    url: jdbc:mysql://114.203.210.122:3306/kosmeeting?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: kosmeeting
    password: ${DATABASE_PWD_KOSMEETING}