import {
    Activity,
    Building2,
    CalendarDays,
    CalendarClock,
    Database,
    Braces,
    FileText,
    Globe2,
    HandHeart,
    Image,
    LineChart,
    LibraryBig,
    Layout,
    ListTree,
    Mail,
    MessageSquare,
    Monitor,
    Mic,
    Network,
    ClipboardCheck,
    ClipboardList,
    CreditCard,
    ScanSearch,
    ShieldCheck,
    Settings,
    Users,
    Wrench,
    type LucideIcon
} from 'lucide-react';

export const NAV_ICON_BY_KEY: Record<string, LucideIcon> = {
    dashboard: LineChart,
    'dashboard-overview': LineChart,
    'dashboard-operation-status': Activity,
    'dashboard-board': Monitor,
    'dashboard-registration': CreditCard,
    'dashboard-abstracts': FileText,
    'dashboard-user-analytics': Monitor,
    'dashboard-user-analytics-details': Monitor,
    abstracts: FileText,
    'abstract-similarity-reviews': ScanSearch,
    'my-reviews': ClipboardCheck,
    'abstract-evaluation-items': ClipboardCheck,
    members: Users,
    'member-registration': Users,
    'society-members': Users,
    'free-recipients': Users,
    countries: Globe2,
    commoncode: Braces,
    admin: ShieldCheck,
    system: Settings,
    'ip-allowlist': Network,
    'access-requests': ShieldCheck,
    conference: CalendarDays,
    menu: ListTree,
    popup: Image,
    'popup-layout': Layout,
    'pre-registrations': ClipboardList,
    program: CalendarClock,
    'abstract-program': CalendarClock,
    sponsors: Building2,
    speakers: Mic,
    sponsorship: HandHeart,
    'promotional-mail': Mail,
    'mail-history': Mail,
    sms: MessageSquare,
    testdata: Database,
    'payment-test': CreditCard,
    'information-resources': LibraryBig,
    'admin-board': MessageSquare,
    'maintenance-requests': Wrench
};
